"""Compliance regime definitions — log types, exclusions, and setup questions."""

REGIMES = {
    "hipaa": {
        "name": "HIPAA",
        "description": "Healthcare data protection (15 PHI identifier categories excluded)",
        "log_types": [
            "Access events (who accessed what data, when)",
            "Data handling decisions (create, read, update, delete)",
            "Consent verification events",
            "Authorization checks",
            "Audit trail entries with timestamps",
            "Minimum necessary determinations",
            "Breach detection events",
        ],
        "exclusions": [
            "Patient names",
            "Dates (birth, admission, discharge, death)",
            "Social Security numbers",
            "Medical record numbers",
            "Health plan beneficiary numbers",
            "Account numbers",
            "Certificate/license numbers",
            "Vehicle/device identifiers and serial numbers",
            "Web URLs and IP addresses",
            "Biometric identifiers",
            "Full-face photographs",
            "Any other unique identifying number or code",
            "Phone and fax numbers",
            "Email addresses (in health context)",
            "Geographic data smaller than state level",
        ],
        "questions": [
            {
                "key": "covered_entity",
                "prompt": "Is your organization a HIPAA covered entity or business associate?",
                "type": "yesno",
                "required": True,
            },
            {
                "key": "phi_handling",
                "prompt": "Does your agent handle Protected Health Information (PHI)?",
                "type": "yesno",
                "required": True,
            },
            {
                "key": "breach_notify_email",
                "prompt": "Email address for breach notification alerts (leave blank to skip):",
                "type": "text",
                "required": False,
            },
        ],
    },
    "eu-ai-act": {
        "name": "EU AI Act",
        "description": "AI transparency and risk management (EU regulation)",
        "log_types": [
            "All automated decisions with explanations",
            "Risk classification assessments",
            "Human oversight events and escalations",
            "Data governance actions",
            "Bias monitoring results",
            "Transparency disclosures to users",
            "Model performance metrics",
            "Conformity assessment records",
        ],
        "exclusions": [
            "Personal data without documented consent basis",
            "Biometric data (unless explicitly authorized)",
            "Behavioral profiling data",
            "Real-time biometric identification data",
            "Social scoring inputs or outputs",
            "Data used for emotion recognition (unless safety-critical)",
        ],
        "questions": [
            {
                "key": "risk_level",
                "prompt": "What is your AI system's risk classification?",
                "type": "choice",
                "choices": ["minimal", "limited", "high", "unacceptable"],
                "required": True,
            },
            {
                "key": "human_oversight",
                "prompt": "Is human oversight configured for high-risk decisions?",
                "type": "yesno",
                "required": False,
            },
        ],
    },
    "soc2": {
        "name": "SOC 2",
        "description": "Trust services criteria (security, availability, integrity, confidentiality, privacy)",
        "log_types": [
            "Security events (access, authentication, authorization)",
            "System availability metrics",
            "Processing integrity checks",
            "Confidentiality controls and data classification",
            "Privacy handling events",
            "Change management records",
            "Incident response actions",
            "Vendor/third-party interaction logs",
        ],
        "exclusions": [
            "Authentication credentials (passwords, tokens, keys)",
            "Internal network topology details",
            "Vulnerability scan raw results",
            "Encryption keys or key material",
            "Security configuration details that could aid attackers",
        ],
        "questions": [
            {
                "key": "trust_criteria",
                "prompt": "Which SOC 2 trust service criteria apply?",
                "type": "multichoice",
                "choices": ["Security", "Availability", "Processing Integrity", "Confidentiality", "Privacy"],
                "required": True,
            },
        ],
    },
    "pci-dss": {
        "name": "PCI-DSS",
        "description": "Payment card data protection",
        "log_types": [
            "All access to cardholder data environments",
            "Authentication attempts (success and failure)",
            "Changes to system components",
            "Network monitoring events",
            "Security testing results (pass/fail only)",
            "Encryption status checks",
            "Key management events",
            "Firewall and access control changes",
        ],
        "exclusions": [
            "Full card numbers (Primary Account Numbers) -- mask to first 6 / last 4 only",
            "Card verification values (CVV, CVC, CID)",
            "PINs and PIN blocks",
            "Magnetic stripe data",
            "Sensitive authentication data after authorization",
            "Full track data from cards",
        ],
        "questions": [
            {
                "key": "saq_type",
                "prompt": "Which PCI-DSS SAQ type applies to your environment?",
                "type": "choice",
                "choices": ["SAQ-A", "SAQ-A-EP", "SAQ-B", "SAQ-C", "SAQ-D", "unsure"],
                "required": False,
            },
        ],
    },
    "nist-ai-rmf": {
        "name": "NIST AI RMF",
        "description": "AI risk management framework (Govern, Map, Measure, Manage)",
        "log_types": [
            "Risk identification and assessment events (MAP)",
            "Risk measurement and metrics (MEASURE)",
            "Risk management actions taken (MANAGE)",
            "Governance decisions and policy changes (GOVERN)",
            "Stakeholder engagement records",
            "Testing and evaluation results",
            "Deployment context documentation",
            "Feedback and incident reports",
        ],
        "exclusions": [
            "Classified or restricted government data",
            "Personal data outside documented use case",
            "Proprietary model weights or architecture details",
            "Raw security vulnerability data",
        ],
        "questions": [
            {
                "key": "rmf_functions",
                "prompt": "Which RMF functions are you implementing?",
                "type": "multichoice",
                "choices": ["Govern", "Map", "Measure", "Manage"],
                "required": True,
            },
        ],
    },
    "generic-trust": {
        "name": "Generic Trust",
        "description": "Basic transparency logging (reasoning, decisions, errors)",
        "log_types": [
            "Reasoning steps and decision rationale",
            "Data sources consulted",
            "Actions taken and their outcomes",
            "Errors and exception events",
            "User interaction events",
            "Confidence levels for decisions",
            "Tool and API calls made",
        ],
        "exclusions": [
            "User credentials and authentication tokens",
            "Private API keys",
            "Personal data not relevant to the logged decision",
        ],
        "questions": [],
    },
    "insurance": {
        "name": "Insurance",
        "description": "Claims and underwriting compliance (policyholder data protection)",
        "log_types": [
            "Claims processing decisions with rationale",
            "Underwriting assessments and factors",
            "Actuarial data handling events",
            "Regulatory compliance checks",
            "Policy issuance and modification events",
            "Fraud detection signals",
            "Premium calculation audit trail",
            "Policyholder communication records",
        ],
        "exclusions": [
            "Policyholder personally identifiable information (PII)",
            "Claims details with identifying information",
            "Medical records and health data (unless HIPAA also selected)",
            "Financial account numbers",
            "Driver license numbers",
            "Beneficiary personal details",
        ],
        "questions": [
            {
                "key": "insurance_type",
                "prompt": "What type of insurance does your agent handle?",
                "type": "choice",
                "choices": ["health", "auto", "property", "life", "commercial", "multi-line"],
                "required": False,
            },
        ],
    },
}
